import { CVTemplate, TemplateCategory } from "@/types";

export const templates: CVTemplate[] = [
  {
    id: "classic-professional",
    name: "Classic Professional",
    description: "Traditional single-column CV with strong hierarchy and formal typography. Perfect for corporate and government roles.",
    bestFor: ["Corporate", "Government", "Finance", "Administration", "Law"],
    category: "classic",
    layoutType: "single-column",
    headerStyle: "centered",
    sectionStyle: "underline",
    experienceStyle: "standard",
    skillsStyle: "comma-list",
    supportsPhoto: false,
    supportsSidebar: false,
    atsSafe: true,
    premium: false,
    visualStyles: ["classic", "minimal", "executive"],
  },
  {
    id: "modern-sidebar",
    name: "Modern Sidebar",
    description: "Two-column layout with a colored sidebar for contact info, skills, and languages. Clean and professional.",
    bestFor: ["Tech", "Marketing", "Business", "Consulting"],
    category: "modern",
    layoutType: "sidebar-left",
    headerStyle: "split",
    sectionStyle: "background-block",
    experienceStyle: "standard",
    skillsStyle: "tags",
    supportsPhoto: true,
    supportsSidebar: true,
    atsSafe: false,
    premium: false,
    visualStyles: ["modern", "two-column"],
  },
  {
    id: "minimalist",
    name: "Minimalist",
    description: "Extremely clean with generous whitespace. No decorative elements. Content speaks for itself.",
    bestFor: ["Design", "Writing", "Research", "Consulting"],
    category: "minimal",
    layoutType: "single-column",
    headerStyle: "minimal",
    sectionStyle: "plain",
    experienceStyle: "compact",
    skillsStyle: "comma-list",
    supportsPhoto: false,
    supportsSidebar: false,
    atsSafe: true,
    premium: false,
    visualStyles: ["minimal", "classic"],
  },
  {
    id: "executive",
    name: "Executive",
    description: "Bold header with leadership focus. Designed for senior professionals and C-suite candidates.",
    bestFor: ["Executive", "Management", "Director", "VP", "C-Suite"],
    category: "executive",
    layoutType: "single-column",
    headerStyle: "bold-block",
    sectionStyle: "boxed",
    experienceStyle: "detailed",
    skillsStyle: "grouped",
    supportsPhoto: true,
    supportsSidebar: false,
    atsSafe: true,
    premium: false,
    visualStyles: ["executive", "classic"],
  },
  {
    id: "timeline",
    name: "Timeline",
    description: "Visual timeline for work experience and education. Shows career progression at a glance.",
    bestFor: ["Career Changers", "Progressive Roles", "Growth Stories"],
    category: "modern",
    layoutType: "timeline",
    headerStyle: "left-aligned",
    sectionStyle: "plain",
    experienceStyle: "timeline",
    skillsStyle: "tags",
    supportsPhoto: false,
    supportsSidebar: false,
    atsSafe: false,
    premium: false,
    visualStyles: ["modern", "two-column"],
  },
  {
    id: "compact-ats",
    name: "Compact ATS",
    description: "Strictly ATS-optimized single-column layout. Maximum content, zero formatting tricks.",
    bestFor: ["Online Applications", "ATS Systems", "High-Volume Applying"],
    category: "ats",
    layoutType: "single-column",
    headerStyle: "left-aligned",
    sectionStyle: "plain",
    experienceStyle: "compact",
    skillsStyle: "comma-list",
    supportsPhoto: false,
    supportsSidebar: false,
    atsSafe: true,
    premium: false,
    visualStyles: ["compact", "minimal"],
  },
  {
    id: "modern-header",
    name: "Modern Header",
    description: "Large full-width header with prominent name and title. Clean sections below.",
    bestFor: ["Marketing", "Sales", "Business Development", "HR"],
    category: "modern",
    layoutType: "single-column",
    headerStyle: "full-width-bar",
    sectionStyle: "background-block",
    experienceStyle: "standard",
    skillsStyle: "tags",
    supportsPhoto: true,
    supportsSidebar: false,
    atsSafe: false,
    premium: false,
    visualStyles: ["modern", "creative"],
  },
  {
    id: "split-profile",
    name: "Split Profile",
    description: "Profile section visually separated from experience. Editorial-style layout with distinct sections.",
    bestFor: ["Marketing", "Communications", "Public Relations", "Media"],
    category: "modern",
    layoutType: "two-column",
    headerStyle: "split",
    sectionStyle: "bordered-left",
    experienceStyle: "standard",
    skillsStyle: "two-column",
    supportsPhoto: true,
    supportsSidebar: true,
    atsSafe: false,
    premium: true,
    visualStyles: ["editorial", "two-column", "creative"],
  },
  {
    id: "creative-portfolio",
    name: "Creative Portfolio",
    description: "Expressive layout for designers and creatives. Distinctive typography with project emphasis.",
    bestFor: ["Design", "Photography", "Art", "Marketing", "Content Creation"],
    category: "creative",
    layoutType: "two-column",
    headerStyle: "editorial",
    sectionStyle: "numbered",
    experienceStyle: "card",
    skillsStyle: "proficiency-grid",
    supportsPhoto: true,
    supportsSidebar: true,
    atsSafe: false,
    premium: true,
    visualStyles: ["creative", "editorial", "two-column"],
  },
  {
    id: "tech-developer",
    name: "Tech Developer",
    description: "Built for developers. Skills grouped by category, projects prioritized, GitHub prominent.",
    bestFor: ["Software Engineering", "Data Science", "DevOps", "IT"],
    category: "technical",
    layoutType: "sidebar-left",
    headerStyle: "left-aligned",
    sectionStyle: "background-block",
    experienceStyle: "detailed",
    skillsStyle: "grouped",
    supportsPhoto: false,
    supportsSidebar: true,
    atsSafe: false,
    premium: false,
    visualStyles: ["technical", "modern", "two-column"],
  },
  {
    id: "academic-research",
    name: "Academic / Research",
    description: "Education-first layout with publications, research interests, and academic achievements.",
    bestFor: ["Academia", "Research", "Teaching", "PhD Candidates", "Students"],
    category: "academic",
    layoutType: "single-column",
    headerStyle: "centered",
    sectionStyle: "underline",
    experienceStyle: "detailed",
    skillsStyle: "grouped",
    supportsPhoto: false,
    supportsSidebar: false,
    atsSafe: true,
    premium: false,
    visualStyles: ["classic", "minimal"],
  },
  {
    id: "elegant-editorial",
    name: "Elegant Editorial",
    description: "Magazine-inspired layout with sophisticated typography. Asymmetric but balanced composition.",
    bestFor: ["Creative Directors", "Senior Designers", "Writers", "Brand Managers"],
    category: "creative",
    layoutType: "editorial",
    headerStyle: "editorial",
    sectionStyle: "bordered-left",
    experienceStyle: "detailed",
    skillsStyle: "two-column",
    supportsPhoto: true,
    supportsSidebar: false,
    atsSafe: false,
    premium: true,
    visualStyles: ["elegant", "editorial", "creative"],
  },
];

export function getTemplateById(id: string): CVTemplate {
  return templates.find((t) => t.id === id) || templates[0];
}

export function getTemplatesByCategory(category: TemplateCategory): CVTemplate[] {
  return templates.filter((t) => t.category === category);
}

export function getFreeTemplates(): CVTemplate[] {
  return templates.filter((t) => !t.premium);
}

export function getPremiumTemplates(): CVTemplate[] {
  return templates.filter((t) => t.premium);
}

export function getATSTemplates(): CVTemplate[] {
  return templates.filter((t) => t.atsSafe);
}

export type TemplateCategoryFilter = TemplateCategory | "all";

export function filterTemplates(category: TemplateCategoryFilter): CVTemplate[] {
  if (category === "all") return templates;
  return templates.filter((t) => t.category === category);
}
